### ISSUE TITLE
Getting error in android versions <5

### ISSUE THREAD

**Issue by iampawan** [generic-leo/SimpleArcLoader#2]
Fatal Exception: android.view.InflateException: Binary XML file line #19: Error inflating class <unknown>
       at android.view.LayoutInflater.createView(LayoutInflater.java:620)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
       at android.app.Dialog.setContentView(Dialog.java:477)
       at com.leo.simplearcloader.SimpleArcDialog.onCreate(SimpleArcDialog.java:67)
       at android.app.Dialog.dispatchOnCreate(Dialog.java:361)
       at android.app.Dialog.show(Dialog.java:262)

```
   at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:338)
   at android.view.View.performClick(View.java:4478)
   at com.pk.Fragment$8$2.onTextChanged(HomeFragment.java:958)
   at android.widget.TextView.sendOnTextChanged(TextView.java:7532)
   at android.widget.TextView.handleTextChanged(TextView.java:7591)
   at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:9585)
   at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:962)
   at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:496)
   at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:435)
   at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:30)
   at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:121)
   at android.widget.TextView.doKeyDown(TextView.java:5641)
   at android.widget.TextView.onKeyDown(TextView.java:5452)
   at android.view.KeyEvent.dispatch(KeyEvent.java:2700)
   at android.view.View.dispatchKeyEvent(View.java:7717)
   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1408)
   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1408)
   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1408)
   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1408)
   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1408)
   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1408)
   at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2038)
   at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1508)
   at android.app.Dialog.dispatchKeyEvent(Dialog.java:712)
   at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1965)
   at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3880)
   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3854)
   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3419)
   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3469)
   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3438)
   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3545)
   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3446)
   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3602)
   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3419)
   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3469)
   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3438)
   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3446)
   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3419)
   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5694)
   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5674)
   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5645)
   at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3210)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:149)
   at android.app.ActivityThread.main(ActivityThread.java:5257)
   at java.lang.reflect.Method.invokeNative(Method.java)
   at java.lang.reflect.Method.invoke(Method.java:515)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
   at dalvik.system.NativeStart.main(NativeStart.java)
```

Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
       at android.app.Dialog.setContentView(Dialog.java:477)
       at com.leo.simplearcloader.SimpleArcDialog.onCreate(SimpleArcDialog.java:67)
       at android.app.Dialog.dispatchOnCreate(Dialog.java:361)
       at android.app.Dialog.show(Dialog.java:262)
       at com.sanaroopay.payoye.activity.HomeFragment.loginClicked(HomeFragment.java:2794)
       at com.sanaroopay.payoye.activity.HomeFragment$8$1.onInput(HomeFragment.java:940)
       at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:338)
       at android.view.View.performClick(View.java:4478)
       at com.pk.Fragment$8$2.onTextChanged(HomeFragment.java:958)
       at android.widget.TextView.sendOnTextChanged(TextView.java:7532)
       at android.widget.TextView.handleTextChanged(TextView.java:7591)
       at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:9585)
       at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:962)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:496)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:435)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:30)
       at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:121)
       at android.widget.TextView.doKeyDown(TextView.java:5641)
       at android.widget.TextView.onKeyDown(TextView.java:5452)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2700)
       at android.view.View.dispatchKeyEvent(View.java:7717)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1408)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1408)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1408)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1408)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1408)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1408)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2038)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1508)
       at android.app.Dialog.dispatchKeyEvent(Dialog.java:712)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1965)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3880)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3854)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3419)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3469)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3438)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3545)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3446)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3602)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3419)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3469)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3438)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3446)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3419)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5694)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5674)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5645)
       at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3210)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:149)
       at android.app.ActivityThread.main(ActivityThread.java:5257)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NumberFormatException: Invalid int: "null"
       at java.lang.Integer.invalidInt(Integer.java:137)
       at java.lang.Integer.parseInt(Integer.java:354)
       at java.lang.Integer.parseInt(Integer.java:331)
       at com.leo.simplearcloader.SimpleArcLoader.readFromAttributes(SimpleArcLoader.java:97)
       at com.leo.simplearcloader.SimpleArcLoader.init(SimpleArcLoader.java:76)
       at com.leo.simplearcloader.SimpleArcLoader.<init>(SimpleArcLoader.java:56)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
       at android.app.Dialog.setContentView(Dialog.java:477)
       at com.leo.simplearcloader.SimpleArcDialog.onCreate(SimpleArcDialog.java:67)
       at android.app.Dialog.dispatchOnCreate(Dialog.java:361)
       at android.app.Dialog.show(Dialog.java:262)
       at com.sanaroopay.payoye.activity.HomeFragment.loginClicked(HomeFragment.java:2794)
       at com.sanaroopay.payoye.activity.HomeFragment$8$1.onInput(HomeFragment.java:940)
       at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:338)
       at android.view.View.performClick(View.java:4478)

```
   at com.pk.app.Fragment$8$2.onTextChanged(HomeFragment.java:958)
   at android.widget.TextView.sendOnTextChanged(TextView.java:7532)
   at android.widget.TextView.handleTextChanged(TextView.java:7591)
   at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:9585)
   at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:962)
   at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:496)
   at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:435)
   at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:30)
   at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:121)
   at android.widget.TextView.doKeyDown(TextView.java:5641)
   at android.widget.TextView.onKeyDown(TextView.java:5452)
   at android.view.KeyEvent.dispatch(KeyEvent.java:2700)
   at android.view.View.dispatchKeyEvent(View.java:7717)
   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1408)
   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1408)
   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1408)
   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1408)
   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1408)
   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1408)
   at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2038)
   at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1508)
   at android.app.Dialog.dispatchKeyEvent(Dialog.java:712)
   at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1965)
   at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3880)
   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3854)
   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3419)
   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3469)
   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3438)
   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3545)
   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3446)
   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3602)
   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3419)
   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3469)
   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3438)
   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3446)
   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3419)
   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5694)
   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5674)
   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5645)
   at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3210)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:149)
   at android.app.ActivityThread.main(ActivityThread.java:5257)
   at java.lang.reflect.Method.invokeNative(Method.java)
   at java.lang.reflect.Method.invoke(Method.java:515)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
   at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by prathameshsawant9** [comment]
Hi , this issue has been fixed now ! My bad i missed this silly one by simply not checking it on < 5 android versions
